apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: ssh-check
  namespace: kuberhealthy
spec:
  runInterval: 5m
  timeout: 2m
  extraAnnotations:
    comcast.com/testAnnotation: test.annotation
  extraLabels:
    testLabel: testLabel
  podSpec:
    containers:
      - name: minio-test
        image: kuberhealthy/ssh-check:v1.0.0
        imagePullPolicy: IfNotPresent
        env:
          - name: SSH_PRIVATE_KEY
            value: "CHANGE_ME"
          - name: SSH_USERNAME
            value: "CHANGEME"
          - name: SSH_EXCLUDE_LIST
            value: "CHANGEME1 CHANGEME2"
        resources:
          requests:
            cpu: 10m
            memory: 50Mi