name: Validate image build

on:
  pull_request:
    branches:
      - main
    paths:
      - "Dockerfile"
      - "go.mod"
      - "go.sum"
      - "cmd/**"
      - ".github/workflows/validate-image-build.yaml"
      - ".github/workflows/publish-tag.yaml"
      - ".github/workflows/publish.yaml"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: false
